### ISSUE TITLE
how to stop commands(or service) managed by Golet?

### ISSUE THREAD

**Issue by yasu47b** [Code-Hex/golet#1]
I tried Golet in my Chromebook using golet/eg/main.go.

I commented out "placup" as a golet service, then fixed cron's schedule 
`30 * * * * *` to `* * * * * *` (this mean execute every minutes).

then execute it 
```
go run main.go
```

cron service works fine!

but I can't stop this cron service.
because chromebook doesn't have a utility command of services like "service" or "crontab".

I also tried to stop using `kill` command.
but crons message still repeated.
(finally I managed to stop cron searching /proc dir just checking /proc/$PID/exe.)

Could you tell me how to stop service?

**Comment by Code-Hex** [comment]
@yasu47b fixed this issue. plz try it!!
